# Site settings
title: 物理实验协会
description: 安徽农业大学物理实验协会
keywords: Physcial,Project, Recording
author: 物理实验协会
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ahau-physcial.github.io" # the base hostname & protocol for your site
